export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";

export const ALERT_SUCCESS = "ALERT_SUCCESS";
export const ALERT_ERROR = "ALERT_ERROR";
export const ALERT_CLEAR = "ALERT_CLEAR";

export const EMPLOYEES_REQUEST = "EMPLOYEES_REQUEST";
export const EMPLOYEES_SUCCESS = "EMPLOYEES_SUCCESS";
export const EMPLOYEES_FAILURE = "EMPLOYEES_FAILURE";

export const EMPLOYEE_DETAILS_REQUEST = "EMPLOYEE_DETAILS_REQUEST";
export const EMPLOYEE_DETAILS_SUCCESS = "EMPLOYEE_DETAILS_SUCCESS";
export const EMPLOYEE_DETAILS_FAILURE = "EMPLOYEE_DETAILS_FAILURE";

export const EMPLOYEE_DELETE_REQUEST = "EMPLOYEE_DELETE_REQUEST";
export const EMPLOYEE_DELETE_SUCCESS = "EMPLOYEE_DELETE_SUCCESS";
export const EMPLOYEE_DELETE_FAILURE = "EMPLOYEE_DELETE_FAILURE";

export const EMPLOYEE_ADD_REQUEST = "EMPLOYEE_ADD_REQUEST";
export const EMPLOYEE_ADD_SUCCESS = "EMPLOYEE_ADD_SUCCESS";
export const EMPLOYEE_ADD_FAILURE = "EMPLOYEE_ADD_FAILURE";

export const EMPLOYEE_EDIT_REQUEST = "EMPLOYEE_EDIT_REQUEST";
export const EMPLOYEE_EDIT_SUCCESS = "EMPLOYEE_EDIT_SUCCESS";
export const EMPLOYEE_EDIT_FAILURE = "EMPLOYEE_EDIT_FAILURE";

export const TECH_SKILLS_REQUEST = "TECH_SKILLS_REQUEST";
export const TECH_SKILLS_SUCCESS = "TECH_SKILLS_SUCCESS";
export const TECH_SKILLS_FAILURE = "TECH_SKILLS_FAILURE";

export const SOFT_SKILLS_REQUEST = "SOFT_SKILLS_REQUEST";
export const SOFT_SKILLS_SUCCESS = "SOFT_SKILLS_SUCCESS";
export const SOFT_SKILLS_FAILURE = "SOFT_SKILLS_FAILURE";

export const COPY_EMPLOYEE = "COPY_EMPLOYEE";
export const CLEAR_COPY_EMPLOYEE = "CLEAR_COPY_EMPLOYEE";
